name: FormatComments
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  path:
#  localstorage:
#    path: ../dart_packages/localstorage

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
